-- Script: historial de personalizaciones por usuario
-- Crea una fila por cada publicación hecha desde /api/file/:id/publish
-- Ejecutar en el SQL editor de Supabase.

BEGIN;

CREATE TABLE IF NOT EXISTS public.user_file_customizations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NULL REFERENCES public.users(id) ON DELETE SET NULL,
  supabase_user_id UUID NULL,
  user_email TEXT NULL,
  original_file_id INTEGER NOT NULL REFERENCES public.html_files(id) ON DELETE CASCADE,
  original_file_name TEXT NULL,
  published_url TEXT NOT NULL,
  published_path TEXT NULL,
  source_filename TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_file_customizations_user_id
  ON public.user_file_customizations(user_id);

CREATE INDEX IF NOT EXISTS idx_user_file_customizations_user_email
  ON public.user_file_customizations(user_email);

CREATE INDEX IF NOT EXISTS idx_user_file_customizations_supabase_user_id
  ON public.user_file_customizations(supabase_user_id);

CREATE INDEX IF NOT EXISTS idx_user_file_customizations_original_file_id
  ON public.user_file_customizations(original_file_id);

CREATE INDEX IF NOT EXISTS idx_user_file_customizations_created_at
  ON public.user_file_customizations(created_at DESC);

-- Trigger para mantener updated_at actualizado en cambios
CREATE OR REPLACE FUNCTION public.set_user_file_customizations_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_user_file_customizations_updated_at ON public.user_file_customizations;
CREATE TRIGGER trg_user_file_customizations_updated_at
BEFORE UPDATE ON public.user_file_customizations
FOR EACH ROW
EXECUTE FUNCTION public.set_user_file_customizations_updated_at();

COMMIT;
